// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BigIntInput: typeof import('./src/components/common/big-int-input.vue')['default']
    Elgamal: typeof import('./src/components/elgamal/elgamal.vue')['default']
    ElgamalDecrypt: typeof import('./src/components/elgamal/elgamal-decrypt.vue')['default']
    ElgamalEncrypt: typeof import('./src/components/elgamal/elgamal-encrypt.vue')['default']
    ElgamalKeygen: typeof import('./src/components/elgamal/elgamal-keygen.vue')['default']
    FileLoadButton: typeof import('./src/components/common/file-load-button.vue')['default']
    FileSaveButton: typeof import('./src/components/common/file-save-button.vue')['default']
    Rsa: typeof import('./src/components/rsa.vue')['default']
    RsaCipherInput: typeof import('./src/components/rsa-cipher-input.vue')['default']
    TextInput: typeof import('./src/components/common/text-input.vue')['default']
  }
}

export { }
