// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BigIntInput: typeof import('./src/components/common/big-int-input.vue')['default']
    Ecc: typeof import('./src/components/ecc/ecc.vue')['default']
    EccDecrypt: typeof import('./src/components/ecc/ecc-decrypt.vue')['default']
    EccEncrypt: typeof import('./src/components/ecc/ecc-encrypt.vue')['default']
    EccKeygen: typeof import('./src/components/ecc/ecc-keygen.vue')['default']
    Elgamal: typeof import('./src/components/elgamal/elgamal.vue')['default']
    ElgamalCipherInput: typeof import('./src/components/elgamal/elgamal-cipher-input.vue')['default']
    ElgamalDecrypt: typeof import('./src/components/elgamal/elgamal-decrypt.vue')['default']
    ElgamalEncrypt: typeof import('./src/components/elgamal/elgamal-encrypt.vue')['default']
    ElgamalKeygen: typeof import('./src/components/elgamal/elgamal-keygen.vue')['default']
    FileLoadButton: typeof import('./src/components/common/file-load-button.vue')['default']
    FileSaveButton: typeof import('./src/components/common/file-save-button.vue')['default']
    Rsa: typeof import('./src/components/rsa/rsa.vue')['default']
    RsaCipherInput: typeof import('./src/components/rsa/rsa-cipher-input.vue')['default']
    RsaDecrypt: typeof import('./src/components/rsa/rsa-decrypt.vue')['default']
    RsaEncrypt: typeof import('./src/components/rsa/rsa-encrypt.vue')['default']
    RsaKeygen: typeof import('./src/components/rsa/rsa-keygen.vue')['default']
    RsaOld: typeof import('./src/components/rsa-old.vue')['default']
    TextInput: typeof import('./src/components/common/text-input.vue')['default']
  }
}

export { }
